version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vitel-backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/db.sqlite3:/app/db.sqlite3
      - /home:/home:ro
      - /root:/root:ro
    networks:
      - vitel-network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vitel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vitel-network
  
networks:
  vitel-network:
    name: vitel-network
    driver: bridge
