# Generated by Codex
from django.db import migrations, models


def mark_configured_profiles(apps, schema_editor):
    UserProfile = apps.get_model('auth_app', 'UserProfile')
    RBACGroup = apps.get_model('auth_app', 'RBACGroup')
    for profile in UserProfile.objects.all():
        has_direct_operations = bool((profile.operations or '').strip())
        has_group = RBACGroup.objects.filter(users=profile.user_id).exists()
        if has_direct_operations or has_group:
            profile.operations_configured = True
            profile.save(update_fields=['operations_configured'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_rbac_and_deployment_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='operations_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_configured_profiles, migrations.RunPython.noop),
    ]
