# Generated by Codex on 2026-06-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0011_registryrepository_registryimage_deploymentjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycledContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(blank=True, max_length=150)),
                ('agent_server_ip', models.CharField(blank=True, max_length=64)),
                ('container_id', models.CharField(max_length=128)),
                ('container_name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('inspect_data', models.JSONField(blank=True, default=dict)),
                ('restored', models.BooleanField(default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('restore_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycled_containers', to='auth_app.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycled_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
