# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_recycledcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recycledcontainer',
            name='target_server_id',
            field=models.CharField(default='local', max_length=64),
        ),
    ]
