# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_recycledcontainer_target_server_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
