from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_detail, name='user_detail'),
    path('change-password/', views.change_password, name='change_password'),
    path('login-history/', views.login_history, name='login_history'),
    path('rbac/', views.rbac_management, name='rbac_management'),
    path('refresh-token/', views.refresh_token, name='refresh_token'),
    path('server-info/', views.server_info, name='server_info'),
    path('agents/', views.agents, name='agents'),
    path('agent-image/', views.agent_image, name='agent_image'),
    path('agent-heartbeat/', views.agent_heartbeat, name='agent_heartbeat'),
    path('agent-command-result/', views.agent_command_result, name='agent_command_result'),
    path('agent-command/', views.agent_command, name='agent_command'),
    path('manual-create-container/', views.manual_create_container, name='manual_create_container'),
    path('container-detail/', views.container_detail, name='container_detail'),
    path('container-monitoring/', views.container_monitoring, name='container_monitoring'),
    path('container-action/', views.container_action, name='container_action'),
    path('container-recycle-bin/', views.container_recycle_bin, name='container_recycle_bin'),
    path('container-network/', views.container_network, name='container_network'),
    path('connect-container/', views.connect_container, name='connect_container'),
    path('connect-volume/', views.connect_volume, name='connect_volume'),
    path('volume-files/', views.volume_files, name='volume_files'),
    path('shell-command/', views.shell_command, name='shell_command'),
    path('shell-output/', views.shell_output, name='shell_output'),
    path('shell-session/', views.shell_session, name='shell_session'),
    path('agent-terminal/', views.agent_terminal, name='agent_terminal'),
    path('browse-dockerfiles/', views.browse_dockerfiles, name='browse_dockerfiles'),
    path('browse-compose-files/', views.browse_compose_files, name='browse_compose_files'),
    path('deployments/', views.deployments, name='deployments'),
    path('deployment-output/<str:job_id>/', views.deployment_output, name='deployment_output'),
    path('deployment-stop/<str:job_id>/', views.stop_deployment, name='stop_deployment'),
    path('deployment-detail/', views.deployment_detail, name='deployment_detail_query'),
    path('deployment-detail/<int:deployment_id>/', views.deployment_detail, name='deployment_detail'),
    path('container-logs/', views.container_logs, name='container_logs'),
    path('container-volume/', views.container_volume, name='container_volume'),
    path('build-image/', views.build_image, name='build_image'),
    path('build-image-output/<str:job_id>/', views.build_image_output, name='build_image_output'),
    path('build-image-stop/<str:job_id>/', views.stop_build_image, name='stop_build_image'),
    path('network/', views.network, name='network'),
    path('volume/', views.volume, name='volume'),
]
